 <h3>Welcome!</h3><br>  Regularly recording your symptoms will help you be more aware of what your body is doing. Symptoms to notice may include - cough, sputum, joint pain, or your bowel motions. By recording your symptoms you will be able to compare from day to day and see changes that may alert you to review your current health care plan. This may help you to recognise at an earlier stage when your health is deteriorating and allow you to act upon this to keep yourself at peak wellness.  <br>
<h2> DISCLAIMER</h2><h4> Your health care team do not view your diary routinely. The purpose of the diary is to allow you to track your own progress and act quickly on any changes. It is your responsibility to notice any changes in your symptoms and we advise you to contact your health care team if your condition is worsening.  </h4>
<br>

<h2>Complete a Baseline Diary?</h2><br> The baseline diary is an opportunity to record what your symptoms are like when you are stable and at your best health. This should be a recent record (i.e. over the last three months), based upon your level of symptoms when you were feeling at your best. Your baseline gives you something to measure change against. So here is what you need to do to complete a baseline diary:<br><ul><li> Think back over the last three months and record your symptoms based on when you felt at your best during this time.</li><li> If you do not record any symptoms over the next three months, you will be asked to repeat your baseline as your health may have changed in this time. </li></ul>

It is important you set this baseline to provide you with something to compare to and see changes in your symptoms. Your baseline symptoms need to reflect your health when you are at your best. When you are setting this baseline think back over the last three months to the time  when you have been at your best health (it may even be right now) and rate your symptoms.

<h2>Complete a Daily Diary?</h2><br> Most people find it difficult to identify small changes in their health. By regularly using the daily diary you will be able to track how your symptoms are changing over time. This may help you to recognise and get treatment for any worsening in your health  before you need to come to hospital. It may also allow you to monitor the effects of new treatments that you have recently started. <br> <h3>A quick guide to using the daily diary:</h3><ol><li>Choose the symptoms you would like to track - everybodys CF symptoms will be different (Settings). You may like to make a record in all of the available symptom choices if this is relevant to you. </li><li>Try to record your symptoms every day (or two), for a few weeks just to become confident and familiar with the website.</li><li>Compare your symptoms to your best health (baseline measurements).</li><li>Keep going - ideally use the daily dairy at least once a week!</li><li>Contact your local CF clinic if you are concerned about any of your symptoms. You may also want to contact your mentor on this website.  </li></ol>Your mentor can provide some support and assistance in interpreting your symptom summaries and will work together with you to encourage you to be proactive in your health care plan.
